package com.github.lukacupic.openskydemo;

public enum Credential {
    OPENSKY_USERNAME, OPENSKY_PASSWORD, GMAIL_USERNAME, GMAIL_PASSWORD,
    BOTTOM_LEFT_LATITUDE, BOTTOM_LEFT_LONGITUDE, TOP_RIGHT_LATITUDE, TOP_RIGHT_LONGITUDE
}